### ISSUE TITLE
Sticky Footer with Font Awesome

### ISSUE THREAD

**Issue by Bruck1701** [antoniolofiego/100DaysOfCloudApp#1]
Hello, 

I created a first draft of a sticky footer based on the wire-frame of the project!  I was not sure where to point the links to yet, so they are still just pointing to the main page. I also installed Font Awesome (free)  to get the icons.

Let me know what you think ! I'll try to tackle the Twitter widget next, unless you have something else in mind. 

🖖

![footer](https://user-images.githubusercontent.com/17711277/88275965-8a1a3200-ccde-11ea-94e7-313c37bd81fe.png)

**Comment by antoniolofiego** [comment]
As mentioned in the fork's comment, replacing the Font Awesome icons with react-icons is the only issue with this, otherwise this looks great to me. Once the dependencies/icons are updated, please open a PR and we are perfect!
